spring.application.name=ai-ui-diplom



# Limits for image generation
image.generation.min-steps=${MIN_STEPS:10}
image.generation.max-steps=${MAX_STEPS:100}

image.generation.min-guidance-scale=${MIN_GUIDANCE_SCALE:1.0}
image.generation.max-guidance-scale=${MAX_GUIDANCE_SCALE:20.0}

image.generation.min-height=${MIN_HEIGHT:256}
image.generation.max-height=${MAX_HEIGHT:1024}

image.generation.min-width=${MIN_WIDTH:256}
image.generation.max-width=${MAX_WIDTH:1024}