"""Initial revision 3

Revision ID: 315da8249bf7
Revises: b67285866b6d
Create Date: 2025-04-24 20:28:03.029253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315da8249bf7'
down_revision: Union[str, None] = 'b67285866b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('images', 'negative_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('negative_prompt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('images', 'image_url')
    # ### end Alembic commands ###
